name: Continuous Integration

on:
  release:
    types: [ published ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-extension:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'automagicallyexecute/package-lock.json'


      - name: install dependencies
        run: npm ci
        working-directory: "automagicallyexecute/"

      - name: install tfx
        run: npm add -g tfx-cli

      - name: build
        run: npm run build
        working-directory: "automagicallyexecute/"

      - name: prune dependencies
        run: npm prune --omit=dev
        working-directory: "automagicallyexecute/"

      - name: tfx publish
        run: tfx extension publish --manifest-globs vss-extension.json -t ${{ secrets.AZURE_PUBLISH_TOKEN }}
