name: Continuous Integration

on:
  #  release:
  #    types: [ published ]
  # TODO revert
  push:
    branches: [ initial-development ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-extension:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: latest

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: 'pnpm-lock.yaml'

      - name: install dependencies
        run: pnpm install

      - name: install tfx
        run: pnpm add -g tfx-cli

      - name: build
        run: pnpm build

      - name: prune dependencies
        run: pnpm prune --prod

      - name: move node_modules
        run: mv -R node_modules automagicallyexecute/

        # node_module symlinks are broken otherwise https://github.com/microsoft/tfs-cli/issues/265#issuecomment-1037307961
      - name: fix node_module links
        run: rsync --archive --verbose --copy-links ./node_modules/ ./node_modules_cp/ && rm -r ./node_modules/ && mv ./node_modules_cp/ ./node_modules/
        working-dir: automagicallyexecute

      - name: tfx publish
        run: tfx extension publish --manifest-globs vss-extension.json --share-with octomind-dev -t ${{ secrets.AZURE_PUBLISH_TOKEN }}
