name: Continuous Integration

on:
  #  release:
  #    types: [ published ]
  # TODO revert
  push:
    branches: [ initial-development ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-extension:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'package-lock.yaml'

      - name: install dependencies
        run: npm ci

      - name: install tfx
        run: npm add -g tfx-cli

      - name: build
        run: npm run build

      - name: prune dependencies
        run: npm prune --omit=dev

      - name: tfx publish
        run: tfx extension publish --manifest-globs vss-extension.json --share-with octomind-dev -t ${{ secrets.AZURE_PUBLISH_TOKEN }}
